# Config file for automatic testing at travis-ci.org

language: python

python:
    - "3.6"

sudo: false

cache:
    directories:
      - $HOME/.cache

dist: trusty

env:
  global:
    - PROJECT_DIR="$PWD"
    - WHEELHOUSE="$HOME/.cache/wheelhouse"

services:
    - postgresql
    - elasticsearch

before_install:
    # cache directories
    - |
      mkdir -p $HOME/.cache/downloads
      mkdir -p $HOME/.cache/pip
      mkdir -p $HOME/.cache/wheelhouse
    # postgres
    - psql -c 'create database travis_ci_test;' -U postgres

install:
    - cd $PROJECT_DIR
    - travis_retry pip install --upgrade pip
    - travis_retry pip install flake8==3.0.4 --force-reinstall --upgrade
    - travis_retry pip install -r dev-requirements.txt
    - travis_retry pip install .

before_script:
  - wget -q --waitretry=1 --retry-connrefused -T 10 -O - http://127.0.0.1:9200

# Run Python tests and flake8
script:
    - flake8 .
    - py.test tests --cov=share --cov=api
    - coverage run --append --source=share,api -m behave

after_success:
    - coveralls
